### ISSUE TITLE
在視窗模式之下無法自動丟鞋

### ISSUE THREAD

**Issue by mmis1000** [howar31/Trove-AHK-AutoFish#1]
貌似是因為圖片被縮放引起的問題
不知道是否有辦法自動調整？
還有請問，那張圖拍攝的視窗大小是？我貌似找不到符合的解析度阿

**Comment by howar31** [comment]
Hmm... 我自己測試好像沒問題，剛剛還在丟鞋，我再找找看原因orz

**Comment by CSFangMS** [comment]
問題應該在於解析度 
視窗模式如果有變更過長寬比 可能會認不出圖片

**Comment by howar31** [comment]
啊！沒錯！就是這樣！
因為目前丟鞋機制是：
1. AHK掃描全螢幕比對boot.bmp
2. 找到完全符合的圖檔就控制滑鼠丟鞋

所以如果畫面上比例改動之類，圖片就不會符合。

這樣的情況只需要自行截圖並裁切鞋子的圖片，然後存成boot.bmp即可！ :smile:

**Comment by mmis1000** [comment]
是說ahk的imagesearch可以掃描subpixel嗎？還是一定要每一個pixel都一致才找得到？昨天也有試過換圖，但是沒效阿

**Comment by mmis1000** [comment]
發現其中一部份是path問題，預設的path是c:/boot.bmp...
有可能做成relative path嗎？
