### ISSUE TITLE
FishAddress

### ISSUE THREAD

**Issue by h78228452** [howar31/Trove-AHK-AutoFish#12]
可以教我怎麼查詢Fish Address 嗎?

**Comment by adioscat** [comment]
我也想學怎麼查詢...
如果方便的話麻煩告之一下,
感恩 :)

**Comment by howar31** [comment]
要拿第三方程式，遊戲內釣魚然後看記憶體變化慢慢找，詳細有點麻煩不好說 :/

**Comment by adioscat** [comment]
好的~
感謝您的答覆 :)

**Comment by adioscat** [comment]
查詢很久找不到方法...
方便的話能給個程式名稱當參考嗎?...
感恩QQ

**Comment by howar31** [comment]
@adioscat 我用的是 Cheat Engine 啦 :P

**Comment by adioscat** [comment]
好的,
感謝你 :)
