### ISSUE TITLE
自動丟鞋有時會因為lag失敗

### ISSUE THREAD

**Issue by mmis1000** [howar31/Trove-AHK-AutoFish#2]
有時會因為lag導致自動丟鞋失敗
而且在hover之後，道具的角度會旋轉
導致之後也無法圖片辨識成功
但是只要把道具欄關掉再重新打開就會重設角度了。
所以這時鞋子又能成功被辨識到。
是否有可能加一個定時重開道具欄的選項？

**Comment by howar31** [comment]
好主意，加在每次釣魚上鉤後兩秒重開欄位好了

**Comment by howar31** [comment]
新版已上線，包含自動重開背包的功能！ :smile:
