### ISSUE TITLE
Reducing cpu usage

### ISSUE THREAD

**Issue by KylinWu** [howar31/Trove-AHK-AutoFish#5]
AutoBootThrow的Timer週期太短，建議設在500ms~1000ms

**Comment by howar31** [comment]
ABT的週期是 [可修改的變數](https://github.com/howar31/Trove-AHK-AutoFish/blob/master/TroveAutoFish.ahk#L18) 讓使用者可以方便自行選用。

當初原本預設是250ms的樣子 (就是SetTimer 的預設值) ，後來發現有時候要手動啟用大量丟鞋會拖太久，曾經還有嘗試過 1ms XD，但速度太快伺服器反應跟不上，因此最後才訂為現在的 100ms 。

已加入註解說明，讓使用者自行決定。 :+1:

**Comment by howar31** [comment]
OK，經過詳細測試， @KylinWu 提到的 ABT 週期預設 100ms 真的太短了點，在低階規格電腦上很吃力，下個版本更新會將預設週期拉長，讓有需要快速的高階規格電腦玩家自行縮短會比較好。 Orz

**Comment by howar31** [comment]
新版已更新，感謝！ :smile:
